In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [8]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.ones(3,3,2)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [13]:
x = torch.tensor([[1,2,3,4],[5,6,8,2],[6,9,5,0]])

In [14]:
x

tensor([[1, 2, 3, 4],
        [5, 6, 8, 2],
        [6, 9, 5, 0]])

In [15]:
x.shape

torch.Size([3, 4])

In [16]:
x = torch.tensor([1.0,2,3,4])
torch.exp(x)

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

In [17]:
x = torch.arange(12,dtype=torch.float32).reshape(3,4)
y = torch.tensor([[1,2,3,4],[5,6,8,2],[6,9,5,0]])
torch.cat((x,y),dim = 0),torch.cat((x,y),dim = 1)  # 将张量连接在一起

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  8.,  2.],
         [ 6.,  9.,  5.,  0.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  5.,  6.,  8.,  2.],
         [ 8.,  9., 10., 11.,  6.,  9.,  5.,  0.]]))

In [18]:
x == y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False,  True, False, False]])

In [19]:
x.sum()

tensor(66.)

In [20]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [23]:
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [24]:
x[1,2]

tensor(6.)

In [26]:
x[0:2, :] = 100
x

tensor([[100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [  8.,   9.,  10.,  11.]])

In [28]:
before = id(x)
y = y + x
id(y) == before

False

In [29]:
Z = torch.zeros_like(y)
print('id(Z):', id(Z))
Z[:] = x + y
print('id(Z):', id(Z))

id(Z): 1872600110144
id(Z): 1872600110144
